[package]
name = "vm_autoscaler"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
ctrlc = "3.4.7"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.35.2"
virt = "0.4.2"
virt-sys = "0.3.0"
